### ISSUE TITLE
Unable to deploy version 5-fpm with docker-compose

### ISSUE THREAD

**Issue by AmsellemJoseph** [mautic/docker-mautic#253]
Hey all,
Since yesterday, I have been trying to deploy the latest version of Mautic based on the example you give in
docker-mautic/examples/fpm-nginx/docker-compose.yml

I followed your instructions to the letter, but I have this error which keeps looping

```
> mautic_worker_1  | Fatal error: Uncaught Error: Failed opening required 
                     '/var/www/html/vendor/composer/../../docroot/app/AppKernel.php' (include_path='.:/usr/local/lib/php') in 
                     /var/www/html/vendor/composer/autoload_real.php:41
> mautic_worker_1  | Stack trace:
> mautic_worker_1  | #0 /var/www/html/vendor/composer/autoload_real.php(45): {closure}('9de8eb80641f81c...', '/var/www/html/v...')
> mautic_worker_1  | #1 /var/www/html/vendor/autoload.php(25): 
                     ComposerAutoloaderInitaf325ce85282f54a66cd09c4a68a7a26::getLoader()
> mautic_worker_1  | #2 /var/www/html/bin/console(7): require_once('/var/www/html/v...')
> mautic_worker_1  | #3 {main}
> mautic_worker_1  |   thrown in /var/www/html/vendor/composer/autoload_real.php on line 41
> mautic_worker_1  | PHP Warning:  require(/var/www/html/vendor/composer/../../docroot/app/AppKernel.php): Failed to open stream: 
                     No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 41
> mautic_worker_1  | 
```

I'm sure I'm missing something but I can't figure out what.

Thank you very much for your work and your responses 😊.

**Comment by mollux** [comment]
@AmsellemJoseph I can't reproduce this.

when I run `docker-compose up -d` in the `/examples/fpm-nginx` folder, I get a working web, worker and cron container.

Did you make any alterations to the example? if so, can you re-check them? as it seems the `mautic-docroot` volume is missing / not working correcty.

**Comment by AmsellemJoseph** [comment]
Found a solution, thx

**Comment by mollux** [comment]
@AmsellemJoseph can you share your solution so we can see if it's generic enough to add it to the readme?

**Comment by AmsellemJoseph** [comment]
yes sur, I had to create a volume named mautic-docroot, and at the end of the docker-compose file, I had to add this:

```
volumes:
  mautic-docroot:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mautic-docroot
      o: bind

```

**Comment by elclay7** [comment]
> yes sur, I had to create a volume named mautic-docroot, and at the end of the docker-compose file, I had to add this:
> 
> ```
> volumes:
>   mautic-docroot:
>     driver: local
>     driver_opts:
>       type: none
>       device: ${PWD}/mautic-docroot
>       o: bind
> ```

Please could you share the docker-compose, I have tried many ways and it doesn't work, not even the example version that is in the repository works, I hope you can share it

**Comment by IonutOjicaDE** [comment]
Hey there! I'm helping the new maintainers of this repository. It was neglected for some time but that changes now! Could you please re-test if you are still getting this issue so we could focus our limited time on the issues that are still relevant? If there will be no response we'll close this issue in 1 week. It can always be re-opened later on.

**Comment by cibero42** [comment]
Hello, we'll have a look on it after dealing with some priorities!
